export const courseList = {
  level1: [
    {
      id: 2,
      title:
        "Việc không kiểm soát được cảm xúc sẽ phá hủy chính bạn và các mối quan hệ của bạn. Nguyên nhân từ đâu?",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/VuHmEWp.jpg",
      content: [
        "- Những dấu hiệu của chứng rối loạn cảm xúc:",
        "+ Thường xuyên mất kiểm soát trong cảm xúc, buồn vui thất thường.",
        "+ Tình trạng mất ngủ kéo dài không rõ nguyên nhân.",
        "+ Bạn thường xuyên chìm vào những cảm xúc tiêu cực, buồn bã, lo âu trước mọi vấn đề.",
        "+ Cảm xúc dẫn đến những hành vi mất kiểm soát, gây sứt nẻ những mối quan hệ.",
        "+ Bạn cảm thấy lạc lõng trong chính những mối quan hệ xung quanh mình.",
      ],
      benefit: [
        "- Tham gia khoá học để hiểu sâu về những cảm xúc bên trong mình:",
        "+ Tìm ra lý do đằng sau việc mất kiểm soát trong hành vi và cảm xúc.",
        "+ Nguyên nhân vì sao những người khác có cách phản ứng hoàn toàn khác với bạn.",
        "+ Hiểu rõ lý do vì sao cảm xúc gây nên chứng khó ngủ, khiến bạn lo lắng kéo dài.",
        "+ Giải mã nguồn gốc của những suy nghĩ tiêu cực bên trong bạn.",
      ],
      video: "https://www.youtube.com/embed/CEWjEEciwQs",
    },
    {
      id: 1,
      title:
        "Bạn chưa có định hướng cho tương lai? Tại sao? Điều gì đang ngăn cản bạn?",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/2MPkdJL.jpg",
      content: [
        "- Bạn có đang gặp phải những vấn đề sau:",
        "+ Cảm thấy chán nản, không hứng thú với công việc mình lựa chọn.",
        "+ Nhìn về tương lai là những mảng mây đen mù mịt, che hết cả lối đi. ",
        "+ Bạn không cảm thấy muốn thức dậy vào mỗi buổi sáng",
        "+ Không có động lực thoát khỏi những thói quen xấu.",
        "+ Vẫn đang đi tìm đáp án cho câu hỏi 'Mình sống để làm gì?'",
      ],
      benefit: [
        "- Khóa học này nên là sự chựa chọn của bạn vì:",
        "+ Hiểu được nguyên nhân gốc rễ của vấn đề để thoát khỏi những cảm xúc tiêu cực trong tâm trí bấy lâu.",
        "+ Nhìn ra những yếu tố quan trọng trong việc  định hướng để xây dựng tương lai.",
        "+ Lấy lại cho mình nội lực mạnh mẽ thúc đẩy bản thân hướng đến những mục tiêu tốt đẹp trong tương lai.",
      ],
      video: "https://www.youtube.com/embed/_IOaBo7-7Co",
    },
    {
      id: 3,
      title: "Không thể vượt qua Trì Hoãn",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/lwYc1MQ.jpg",
      content: [
        "- Khoá học này sẽ rất cần thiết, nếu bạn đang:",
        "+ Đặt mục tiêu nhưng hiếm khi nào hoàn thành được.",
        "+ Chỉ khi có người đến đốc thúc thì bạn mới có động lực làm việc.",
        '+ Thường xuyên gặp khó khăn trong việc tạo động lực làm việc dẫn đến "nước tới chân mới nhảy".',
        "+ Thường lo ngại, đắn đo khi đứng trước một cơ hội mới nào đó.",
        "+ Không cảm thấy thật sự hạnh phúc và tự hào về chính mình dù đã đạt kết quả rất tốt.",
      ],
      benefit: [
        "- Vì sao bạn cần đến khóa học này?",
        "+ Xác định rõ bạn đang mắc phải vấn đề gì dẫn đến các tình trạng trễ nãi, trì hoãn,... hiện tại ",
        "+ Tìm lại động lực thúc đẩy bản thân thoát khỏi những cảm xúc chán nản giúp đạt hiệu quả trong công việc.",
        "+ Thấu hiểu những suy nghĩ khiến bản thân không thể chủ động và nỗ lực cao trong công việc.",
        "+ Hiểu rõ lý do khiến bạn thường xuyên mất động lực dẫn đến thói quen trì hoãn, lười.",
        "+ Tìm lại cảm giác hạnh phúc thật sự khi hoàn thành nhiệm vụ của mình.",
      ],
      video: "https://www.youtube.com/embed/k8b2fiokAHc",
    },
    {
      id: 9,
      title: "Không thể vượt qua Sự Xao Nhãng",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/ZhSgn9i.jpg",
      content: [
        "- Khoá học này sẽ rất cần thiết, nếu bạn đang:",
        "+ Đặt ra mục tiêu nhưng nhanh chóng mất động lực để hoàn thành.",
        "+ Đang làm việc này thì tâm trí lại đưa mình sang việc khác, kết quả là thường xuyên chậm trễ trong công việc.",
        "+ Không nhất quán với mục tiêu, thường xuyên bị phân tâm, nhiều suy nghĩ tiêu cực bủa vây.",
      ],
      benefit: [
        "- Vì sao bạn cần đến khóa học này?",
        "+ Xác định rõ bạn đang mắc phải vấn đề gì dẫn đến các tình trạng xao nhãng hiện tại",
        "+ Tìm lại cảm giác hạnh phúc thật sự khi hoàn thành nhiệm vụ của mình.",
        "+ Tìm hiểu cách thức để vượt qua thứ đang giữ chân mình.",
      ],
      video: "https://www.youtube.com/embed/W6ASIS_lkhA",
    },
    {
      id: 4,
      title:
        "Tìm hiểu nguyên nhân khiến bạn không thể hiện được suy nghĩ của bạn ra bằng lời nói khiến các mối quan hệ trong cuộc sống trở nên khó gần hơn.",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/rIyHkm6.jpg",
      content: [
        "- Bạn có phải là người giao tiếp kém?",
        "+ Luôn gặp vấn để trong việc kết thân, làm quen với những người xung quanh.",
        "+ Thường rất khổ sở để diễn đạt mong muốn và ý kiến bản thân.",
        "+ Thường bị hiểu lầm vì không biết cách giao tiếp và ứng xử phù hợp.",
        "+ Không thể 'gọi tên' được những cảm xúc bên trong mình, dù là tiêu cực hay tích cực.",
        "+ Đôi khi cảm thấy bối rối, hoang mang, không biết nên xử lý tình huống như thế nào.",
        "+ Bạn nghĩ ra được nhiều thứ nhưng không thể chuyển thành lời để thuyết phục người khác.",
      ],
      benefit: [
        "- Tham gia khoá học để giải quyết vấn đề của mình:",
        "+ Tập hợp những kiến thức giúp bạn tìm ra vấn đề trong giao tiếp trong nhiều hoàn cảnh và tình huống.",
        "+ Tìm ra nguyên nhân vì sao bản thân không thể bày tỏ được những cảm xúc bên trong mình. Có bức tường nào đang cản trở bạn.",
        "+ Nhận thức rõ được rằng lỗi giao tiếp trong các mối quan hệ bắt nguồn từ người khác hay từ bên trong mình.",
      ],
      video: "https://www.youtube.com/embed/JSF69vQdFx0",
    },
    {
      id: 5,
      title: "Thiếu Tự Tin & Giá Trị Tự Thân. Tự Phản Bội Chính Mình",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/RVH7Wud.jpg",

      content: [
        "- Khóa học này rất cần thiết, nếu bạn đang:",
        "+ Cảm thấy bản thân thấp bé, không dám nói lên ý kiến của mình.",
        "+ Không thể đứng trước đám đông để thuyết trình, hùng biện,... hay làm bất cứ điều gì.",
        "+ Đôi khi rất muốn làm một việc gì đó nhưng đắn đo mãi và cuối cùng mất cơ hội.",
        "+ Khi tranh luận, bạn không có đủ can đảm để theo đến cùng & nhất quán với luận điểm của mình.",
      ],
      benefit: [
        "Vì sao bạn nên chọn khóa học này?",
        "+ Khoá học sẽ giúp bạn tìm ra lý do nào đã khiến bạn trở thành con người thiếu tự tin như ngày hôm nay.",
        '+ Để hiểu được "lợi ích đằng sau" của việc thiếu tự tin, khiến rất nhiều người chọn cách này để sống.',
        "+ Nhận thức đúng đắn về giá trị tự tin của một con người & lợi ích của nó.",
      ],
      video: "https://www.youtube.com/embed/zC7py-vSRaM",
    },
    {
      id: 6,
      title:
        "Bạn đã nghiện điện thoại thông minh và các chứng nghiện của thời đại như thế nào?",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/CIG0Dhs.jpg",
      content: [
        "- Khóa học này rất cần thiết, nếu bạn đang:",
        "+ Dành quá nhiều thời gian trong ngày để sử dụng smart phone.",
        "+ Cảm thấy không thể có phút giây nào không có điện thoại kề bên mình.",
        '+ Dùng điện thoại như một thói quen và dần mất kết nối với những "người thật"',
        '+ Bạn bè của bạn hầu như là "Bạn bè Facebook", không thật sự kết nối, trò chuyện với nhau.',
        "+ Bạn không có sở thích cả nhân & sử dụng điện thoại như cách giết thời gian.",
      ],
      benefit: [
        "- Vì sao bạn nên chọn khóa học này?",
        '+ Khoá học sẽ giúp bạn nhận ra bạn có thật sự đang là "con nghiện" smartphone hay không',
        "+ Để bạn tìm ra nguyên nhân vì sao bản thân lại quá lạm dụng nó",
        "+ Để hiểu rõ vấn đề tác hại mà lạm dụng smart-phone mang lại.",
      ],
      video: "https://www.youtube.com/embed/9FrbA_RZSwI",
    },
    {
      id: 7,
      title: "Hiểu về bệnh mất ngủ từ tâm trí",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/yKC5H5U.jpg",
      content: [
        "- Người mất ngủ thường cảm thấy:",
        "+ Sợ hãi và ám ảnh vì đến giờ ngủ lại không ngủ được.",
        "+ Ban ngày cảm thấy buồn ngủ, tâm trí mệt mỏi, lờ đờ khiến hiệu suất làm việc trong ngày giảm mạnh.",
        "+ Bên trong tồn tại những “mối” lo lắng vô hình, không rõ nguyên nhân khiến bản thân mất ngủ.",
        "+ Dồn nén nhiều suy nghĩ luẩn quẩn trong đầu trước khi ngủ.",
        "+ Không cảm thấy được thư giãn trước & sau giấc ngủ.",
      ],
      benefit: [
        "- Khóa học này sẽ giúp ích gì cho bạn?",
        '+ Giải đáp thắc mắc được nhiều người quan tâm nhất: “Mất ngủ có phải là dấu hiệu bệnh lý cần phải "dứt điểm” nhanh chóng?"',
        "+ Vì sao có người uống thuốc thì ngủ được còn bạn thì không?",
        "+ Giải pháp nào là phù hợp để chữa trị chứng mất ngủ dành cho bạn.",
        "+ Hiểu rõ những vấn đề tạo nên chứng mất ngủ gây ra cho bạn.",
      ],
      video: "https://www.youtube.com/embed/zQpK5SnhbFQ",
    },
    {
      id: 8,
      title: "Hiểu về bệnh hay quên từ tâm trí",
      description: "",
      priceNew: 200000,
      priceOld: 400000,
      coach: "giangThanh",
      picture: "https://i.imgur.com/9Yhg7sK.jpg",
      content: [
        "- Chứng hay quên đã cản trở bạn như thế nào?",
        "+ Dễ quên những vấn đề bất chợt, vừa nhớ lại quên ngay trong phút chốc.",
        "+ Phải mất một khoảng thời gian để nhớ hoặc tìm lại những thông tin cũ.",
        "+ Khó khăn trong việc phán đoán và suy luận, vì mất rất lâu để liên kết các dữ liệu thông tin.",
        "+ Khả năng tiếp thu và ghi nhớ kém, kéo năng suất và hiệu quả công việc xuống thấp.",
        "+ Thường xuyên bị khiển trách và phàn nàn vì bị đánh giá là hay lơ là trong công việc.",
      ],
      benefit: [
        "- Lý do bạn nên tham gia khóa học này:",
        "+ Xác định được mức độ nặng - nhẹ về chứng hay quên của bạn.",
        "+ Hiểu rõ nguyên nhân vì sao bạn không thể có trí nhớ tốt như người khác.",
        '+ Hệ thống lại trật tự "tâm trí” trong việc ghi nhớ thông tin, giảm thiểu việc hay quên.',
        "+ Hiểu rõ về tâm trí, hiểu rõ căn nguyên vấn đề của chính mình & những cách thức để khắc phục.",
      ],
      video: "https://www.youtube.com/embed/MFgoJd5GDfs",
    },
  ],
  level2: [
    {
      id: 1,
      title:
        "Kiến tạo tương lai của bạn, Lập kế hoạch & Biến nó thành hiện thực",
      description: "",
      priceNew: 400000,
      priceOld: 800000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/191ab4fd-9c62-4494-b209-51f86a3924d3/product/6076639631b9ae0024d5dab7",
      content: [
        '- "Lập kế hoạch cho tương lai" là điều không hề dễ dàng?',
        "+ Sẽ không phải là vấn đề nếu như bạn biết cách thực hiện nó.",
        "+ Thiết lập cho mình một kế hoạch phù hợp với khả năng, mong muốn, để xây dựng nên thành công theo cách riêng của bạn.",
      ],
      benefit: [
        "- Khoá học mang đến cho bạn giải pháp",
        "+ Giúp bạn hiểu cách thức xây dựng kế hoạch và mục tiêu 2 năm -  5 năm và hơn thế nữa.",
        "+ Biết tự tạo nội động lực cho chính mình, thúc đẩy bản thân hiện thực các mục tiêu đã đề ra.",
        "+ Biết cách xây dựng, phân chia quỹ thời gian để thực hiện kế hoạch tối ưu năng lực & công suất.",
        "+ Nhận thức được yếu tố tạo nên sự khác biệt cho chính bạn để định hướng xây dựng tương lai.",
      ],
      video: "https://www.youtube.com/embed/bO0Gd4kLZ0g",
    },
    {
      id: 2,
      title:
        "Hiểu được những Cảm Xúc Tiêu Cực đến từ đâu, Chữa Lành chúng và Kiểm Soát Cảm Xúc tốt hơn",
      description: "",
      priceNew: 400000,
      priceOld: 800000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/6000fcd544d203002598bd5a",
      content: [
        "- Khi một người biết cách kiểm soát cảm xúc:",
        "+ Người đó sẽ kiểm soát được phần lớn hành vi, tư duy & tâm trạng của họ trong từng khoảnh khắc mỗi ngày.",
        '+ Họ sẽ không dễ dàng bị tác động bởi những người "độc hại" xung quanh.',
        "+ Họ biết được khi nào là lúc cần thiết để giải phóng cảm xúc, khi nào là điểm dừng.",
        "+ Biết cách cư xử đúng mực, hài hoà các mối quan hệ.",
      ],
      benefit: [
        "- Đến với khoá học, bạn sẽ: ",
        "+ Không còn bị lệ thuộc cảm xúc vào cách cư xử của người khác.",
        "+ Cơ thể, tâm trí & cảm xúc của bạn sẽ trở nên bình ổn, an yên trước cuộc sống tấp nập.",
        "+ Biết cách đào thải những điều tiêu cực đang tồn tại bên trong mình, thu nạp những điều tích cực.",
        "+ Luôn quan sát chính mình, tỉnh tảo nhận thức & thay đổi ngay lập tức các hành vi tiêu cực của mình.",
        "+ Từng bước trở thành chủ nhân của cuộc đời mình, thông qua việc kiểm soát cảm xúc, hành vi, tư duy của chính mình. ",
      ],
      video: "https://www.youtube.com/embed/Iu0XPkyRJL8",
    },
    {
      id: 3,
      title:
        "Hiểu được những hành vi tự làm hại bản thân đến từ đâu & Trải nghiệm việc chữa lành chúng",
      description: "",
      priceNew: 400000,
      priceOld: 800000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/5fffc7fe44d203002598bb3e",
      content: [
        "- Lợi ích từ việc xây dựng hành vi tích cực cho bản thân?",
        "+ Dễ dàng hòa nhập và kết nối với cộng đồng bằng tư duy tích cực, lành mạnh.",
        "+ Tăng sự tự tin trong việc thể hiện bản thân và thu hút người khác.",
        "+ Trở nên vui vẻ và lạc quan hơn, tận hưởng cuộc sống này trọn vẹn và tươi vui.",
        "+ Thuận lợi trong việc mở rộng các mối quan hệ, thăng tiến trong công việc.",
        "+  Dễ dàng chữa lành bản thân và thoát khỏi những điều tiêu cực xảy đến với mình.",
      ],
      benefit: [
        "Khóa học sẽ giúp bạn bằng cách:",
        "+ Loại bỏ những tư duy tiêu cực ám ảnh bạn lâu năm thay bằng những tư duy tích cực.",
        "+ Học cách ngăn ngừa những hành vi tiêu cực, tự làm tổn thương đến bản thân.",
        "+ Xoa dịu những thương tổn bên trong và thiết lập nên những hành vi tích cực mới.",
        "+ Xây dựng lối hành vi và lối suy nghĩ của người thành công và hạnh phúc.",
      ],
      video: "https://www.youtube.com/embed/jbkQGe99f5o",
    },
    {
      id: 4,
      title:
        "Trở Nên Lạc Quan, Hình Thành Nội Động Lực & Sống Hòa Hợp với mọi người. Giao Tiếp Tích Cực",
      description: "",
      priceNew: 400000,
      priceOld: 800000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/5ffff8d744d203002598bbce",
      content: [
        "- Giao tiếp tốt sẽ mang lại cho bạn điều gì?",
        "+ Là việc có thể tự tin nói ra những cảm xúc và suy nghĩ của mình trọn vẹn và đầy đủ ý.",
        "+ Kéo gần hơn khoảng cách giữa bạn và các thành viên trong gia đình.",
        "+ Người khác yêu thích việc nói chuyện với bạn vì bạn biết cách truyền nguồn năng lượng tích cực đến mọi người.",
        "+ Nó giúp bạn mở mang kiến thức thông qua việc lắng nghe và chia sẻ; từ đó mở rộng và nâng cao chất lượng mối quan hệ.",
        '+ Giao tiếp tốt giúp bạn "chốt” hợp đồng nhanh chóng và duy trì khách hàng tiềm năng.',
      ],
      benefit: [
        "- Bạn nhận được gì từ khóa học này:",
        "+ Thoát khỏi ám ảnh giao tiếp kém duyên, thiếu ý, nhạt nhẽo.",
        "+ Cải thiện khả năng truyền đạt ý nghĩ và cảm xúc của bản thân đến người khác, tránh việc hiểu lầm hoặc mâu thuẫn đáng tiếc.",
        "+ Tạo sự gần gũi từ bạn, khiến đối phương cảm thấy thoải mái khi trò chuyện và chia sẻ.",
        "+ Mở rộng mối quan hệ với đối tác và duy trì nguồn khách tiềm năng.",
      ],
      video: "https://www.youtube.com/embed/-tiEXAyGUuc",
    },
    {
      id: 5,
      title: "Cách xây dựng lại Sự Tự Tin & Giá Trị Tự Thân",
      description: "",
      priceNew: 400000,
      priceOld: 800000,
      coach: "giangThanh",
      picture:
        "https://kelley-lecture-video.s3-ap-southeast-1.amazonaws.com/VI_1616249177.722_Doc-38.jpg",
      content: [
        "- Lợi ích của việc xây dựng giá trị bản thân là gì?",
        "+ Thấu hiểu bản chất của việc tự hào và khiêm tốn không để bản thân dẫn đến tự kiêu và tự mãn.",
        "+ Thăng tiến trong công việc vì thái độ tự tin và đạt được dự tính nhiệm từ cấp trên.",
        "+ Quan điểm và hành động trở nên nhất quán, không bị ảnh hưởng bởi những tác nhân bên ngoài.",
        "+ Mạnh dạn trong việc đưa ra ý kiến để thảo luận cùng cấp trên, tinh thần trách nhiệm trong công việc cao.",
        "+ Luôn có góc nhìn và tư duy tích cực trong việc đưa ra phương án phù hợp với bản thân nhằm giải quyết vấn đề.",
      ],
      benefit: [
        "Khóa học này mang đến cho bạn:",
        "+ Thay đổi hành động và suy nghĩ từ tiêu cực trở nên tích cực, tạo thiện cảm với đối phương.",
        "+ Cách thức xây dựng và nâng cao giá trị bản thân lâu dài.",
        "+ Từng bước nâng cấp giá trị bản thân, trở nên mạnh mẽ và bản lĩnh hơn trong công việc và cuộc sống.",
        "+ Khiến bạn trở nên tự tin và tràn đầy năng lượng trong việc bộc lộ bản thân trước người khác. ",
      ],
      video: "https://www.youtube.com/embed/tyQ7PQOtf9A",
    },

    {
      id: 6,
      title: "Loại bỏ chứng nghiện, cài đặt hành vi hữu ích và có giá trị",
      description: "Vẽ ước mơ của bạn.",
      priceNew: 400000,
      priceOld: 800000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/6000202444d203002598bd0d",
      content: [],
      benefit: [],
      video: "https://www.youtube.com/embed/Abi6tQKPNrU",
    },

    {
      id: 7,
      title:
        "Chữa lành mọi chứng Bệnh Về Tâm. Trở thành một phiên bản tốt hơn của bạn",
      description: "",
      priceNew: 400000,
      priceOld: 800000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/5fffad6f44d203002598bacd",
      content: [
        "- Tại sao bạn cần nâng cấp bản thân trở nên tốt hơn:",
        "+ Để có nguồn năng lượng tuyệt vời từ bên trong, không bị tác động bởi những điều tiêu cực.",
        "+ Trở thành người luôn bản lĩnh, tỉnh táo xử trí trước mọi tình huống.",
        "+ Trở thành một người đầy tích cực, biết cách giao tiếp đúng đắn với chính mình để phát triển bản thân.",
        "+ Để là một người khoẻ mạnh lẫn về thể chất lẫn tinh thần.",
      ],
      benefit: [
        "- Khoá học mang đến cho bạn những giá trị:",
        "+ Trẻ hoá tâm trí, tái cơ cấu lại những lớp tư duy/ cảm xúc từ não bộ để thay đổi cách nhìn nhận sự việc.",
        "+ Thực hiện các phương pháp để thư giãn đầu óc, thả lỏng tâm trí của chính mình.",
        "+ Khai thác nguồn năng lượng dồi dào từ bên trong mà đã ngủ quên suốt bấy lâu nay.",
        "+ Tự mình đưa ra quyết định trước những biến cố xảy đến một cách thoải mái, nhẹ nhàng, bình an.",
        "+ Làm chủ bí kíp kiểm soát tâm trí và cơ thể, đẩy lùi các loại bệnh do tâm bệnh mà ra.",
      ],
      video: "https://www.youtube.com/embed/gxu66jxc0DA",
    },
  ],
  level3: [
    {
      id: 1,
      title: "Sự Kết Nối Giữa Tâm Trí & Cơ Thể",
      description: "",
      priceNew: 2500000,
      priceOld: 8000000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/191ab4fd-9c62-4494-b209-51f86a3924d3/product/6076639631b9ae0024d5dab7",
      content: [],
      benefit: [],
      video: "https://www.youtube.com/embed/92ZP8onjjqE",
    },
    {
      id: 2,
      title: "Giao Tiếp Hiệu quả",
      description: "",
      priceNew: 3500000,
      priceOld: 8000000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/6000fcd544d203002598bd5a",
      content: [],
      benefit: [],
    },
    {
      id: 3,
      title:
        "Giao Tiếp với Tâm Trí Vô Thức - Kích Hoạt Những Nguồn Lực Từ Bên Trong",
      description: "",
      priceNew: 4500000,
      priceOld: 8000000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/5fffc7fe44d203002598bb3e",
      content: [],
      benefit: [],
    },
    {
      id: 4,
      title: "Kích Hoạt 5 Giác Quan Bên Trong - Hình Dung Tưởng Tượng",
      description: "",
      priceNew: 5500000,
      priceOld: 8000000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/5ffff8d744d203002598bbce",
      content: [],
      benefit: [],
    },
    {
      id: 5,
      title: "Kiểm Soát Căng Thẳng",
      description: "",
      priceNew: 6500000,
      priceOld: 8000000,
      coach: "giangThanh",
      picture:
        "https://kelley-lecture-video.s3-ap-southeast-1.amazonaws.com/VI_1616249177.722_Doc-38.jpg",
      content: [],
      benefit: [],
    },
    {
      id: 6,
      title:
        "Giá Trị & Sức Mạnh của việc Coaching bằng NLP. Cách trở thành người Coach Chuyên Nghiệp",
      description: "",
      priceNew: 7500000,
      priceOld: 8000000,
      coach: "giangThanh",
      picture:
        "https://cdn2.topica.vn/99e8262a-7b95-4050-a1a0-d6977c9d98ed/product/6000202444d203002598bd0d",
      content: [],
      benefit: [],
    },
  ],
};

export const courseLevel = [
  {
    levelId: "level1",
    name: "Level 1",
    description:
      "Understand the problem, Where do you get it from, why do you need to solve it?",
  },
  {
    levelId: "level2",
    name: "Level 2",
    description: "How to solve the Problem & take responsibility",
  },
  {
    levelId: "level3",
    name: "Level 3",
    description: "How to solve the Problem & take responsibility",
  },
];
// các khóa trong level 1 sẽ có id khóa học trùng với khóa học ở level 2
